x=int(input("Nhap X :"))
Y=int(input("Nhap Y :"))
C=str(input("Nhap C :"))
F=float(input("Nhap F :"))
D=float(input("Nhap D :"))
print(x)
print(Y)
print(C)
print(round(F,2))
print(format(D, ".9f"))